name: sled
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - yaml
  - nibabel
  - matplotlib
  - tensorflow
  - pyyaml

# specify the path where the env should be installed
# prefix: /export01/data/Hanwen/software/anaconda3/envs/sled
