io: &paths
  subject_id: &id control_01
  data_path: data/new_data/CALIPR_HC/CALIPR_qT2_SPIRALlongFOVmoreUS_20240808.user_rrdf_20241011_093250_calipr_recon_all.nii
  mask_path: data/new_data/CALIPR_HC/CALIPR_qT2_SPIRALlongFOVmoreUS_20240808.user_rrdf_20241011_093250_calipr_recon_all_mask.nii.gz # if no mask, set to Null or False. However, mask is recommended for better performance
  pretrained_model_path: &pretrained_model_path models/rician.h5
  save_folder_path: &save_folder_path results/rician/test/
  save_prefix: &prefix epg_gaussian
  descrip: many pool with fixed sigma # add descriptive text to header (max 80 chars)

sequence:
  number_of_echoes: &num_te 80 # if less than the total number of echoes in the data, the first n echoes will be used
  first_echo_time: &1st_te 0.00431
  echo_spacing: &delta_te 0.00431

fitting:
  fitting_model: &fitting_model parametric # selections = [parametric, nonparametric]
  decay_model: &decay_model epg # selections = [exp, epg]
  noise_model: &noise_model gaussian # selections = [gaussian, rician]
  normalization: &normalization True  
  fix_sigma: &fix_sigma False
  remove_negative: &remove_negative False # if True, negative values will be set to 0
  pretrain_model: &pretrain False
  mask_mwf_map: &mask_mwf_map False
  load_pretrained_model: &load_pretrained_model False
  save_maps: &save_maps ['mwf', 'amps'] # selections = ['mwf', 't2s', 'amps', 'residuals', 'fitted_signals']

  number_of_pools: &num_pool 3
  mwf_cutoff: &my_t2_cutoff 0.06
  train_iterations: &epochs 1
  batch_size: &batch_size 512
  
  parametric: # a typical 3 pool model
    range_t2_my: &t2s_my [0.01, 0.03]
    range_t2_ie: &t2s_ie [0.09, 0.15]
    range_t2_fr: &t2s_fr [0.5, 1]
    
  nonparametric:
    t2s_range: &t2s_range [0.005, 1]
    basis_t2s: *num_pool

  fix_sigma:
    sigma_value: &sigma_value 0.1

  load_existing_model:
    path: models/rician.h5


preprocessing:
  remove_negative: *remove_negative # if True, negative values will be set to 0
  normalization: *normalization # if True, loss function should be categorical_crossentropy (mse for False)
  mask_threshold: 0.5
  scaling_quantile: 0.99 # to calculate scaling factor and exclude outliers


model: &structure
  encoder:
    name: encoder model
    fitting_model: *fitting_model
    decay_model: *decay_model
    input_shape: *num_te
    latent_shape: *num_pool
    t2s_range: *t2s_range
    range_t2_my: *t2s_my
    range_t2_ie: *t2s_ie
    range_t2_fr: *t2s_fr
    fix_sigma: *fix_sigma
    sigma_value: *sigma_value

    # encoder architecture
    nn_base: mlp # selections = [mlp, resnet]

    base_nn_t2s:
      name: mlp # selections = [mlp, resnet]

    base_nn_amps:
      name: mlp # selections = [mlp, resnet]

    base_mlp_t2:
      hidden_layers: [256, 128]
      num_classes: 1
      activation: sigmoid
      activation_last_layer: sigmoid
      l1_reg: 0
      l2_reg: 0

    base_mlp_amps:
      hidden_layers: [256, 256]
      num_classes: *num_pool
      activation: sigmoid
      activation_last_layer: softmax
      l1_reg: 0.1
      l2_reg: 0
    
    base_mlp_sigma:
      hidden_layers: [256, 128]
      num_classes: 1
      activation: sigmoid
      activation_last_layer: sigmoid
      l1_reg: 0
      l2_reg: 0

    base_mlp_fa:
      hidden_layers: [256, 128]
      num_classes: 1
      activation: sigmoid
      activation_last_layer: sigmoid
      l1_reg: 0
      l2_reg: 0

    base_resnet_t2: 
      hidden_layers_head: [128]
      num_res_blocks: 2
      res_block_size: [256, 256]
      hidden_layers_tail: [128]
      num_classes: 1
      activation: sigmoid
      activation_last_layer: sigmoid
      l1_reg: 0
      l2_reg: 0

    base_resnet_amps: 
      hidden_layers_head: [128]
      num_res_blocks: 2
      res_block_size: [256, 256]
      hidden_layers_tail: [128]
      num_classes: *num_pool
      activation: sigmoid
      activation_last_layer: softmax
      l1_reg: 0
      l2_reg: 0
    
    base_resnet_sigma: 
      hidden_layers_head: [128]
      num_res_blocks: 2
      res_block_size: [256, 256]
      hidden_layers_tail: [128]
      num_classes: *num_pool
      activation: sigmoid
      activation_last_layer: softmax
      l1_reg: 0
      l2_reg: 0

    base_resnet_fa: 
      hidden_layers_head: [128]
      num_res_blocks: 2
      res_block_size: [256, 256]
      hidden_layers_tail: [128]
      num_classes: *num_pool
      activation: sigmoid
      activation_last_layer: softmax
      l1_reg: 0
      l2_reg: 0

  decoder:
    name: decoder
    num_classes: *num_pool
    nte: *num_te
    first_te: *1st_te
    delta_te: *delta_te
    snr_range: Null # [50, 300]
    normalization: *normalization
    fix_t1s: True
    fix_t1s_value: 1.0
    t1_t2_ratio: 5.0 # if fix_t1s is False, t1_t2_ratio will be used to calculate t1s

  
  sled:
    decay_model: *decay_model
    load_pretrained_model: *load_pretrained_model
    pretrained_model_path: *pretrained_model_path

pretrain:
  pretrain_model: *pretrain
  fitting_model: *fitting_model
  number_of_echoes: *num_te 
  first_echo_time: *1st_te
  echo_spacing: *delta_te
  number_of_samples: 100000
  t2_ranges: [*t2s_my, *t2s_ie, *t2s_fr] # simulate for 3 pools
  amplitude_ranges: [[0,0.3],[0,1],[0,0.05]] # for white and grey matter only, csf is simulated independently
  snr_range: &snr_range [30, 100]
  t2_basis_range: *t2s_range  # bigger range to capture the tails
  number_of_t2_basis: *num_pool  # number of log-spaced points in the basis
  gauss_peak_sigma: 1
  csf_sim: True # if True, simulate CSF independently
  csf_n_samples: 20000
  # loss: {'t2s': 'categorical_crossentropy', 'amps': 'categorical_crossentropy', 'fitted_signals': 'rician_nll_loss'}
  # loss_rician_sigma: 0.08
  # loss_weights: {'t2s': 0, 'amps': 50, 'fitted_signals': 0.1}
  # metrics: {'t2s': 'mae', 'amps': 'mae', 'fitted_signals': 'mae'}
  # epochs: 20
  # learning_rate: 0.001
  # batch_size: 512
  # verbose: 1
  # shuffle: True

# Training Configuration
training:
  batch_size: *batch_size            # Number of samples per gradient update
  epochs: *epochs                 # Total number of training epochs

  optimizer:               # Optimizer settings
    learning_rate: 0.001    # Initial learning rate
    clipnorm: Null           # Gradient clipping norm (use 'null' if not applied)
    clipvalue: Null         # Gradient clipping value (use 'null' if not applied)

  noise_model: *noise_model     

  loss_weights:            # (Optional) Weights for each loss function
    multiecho: 1
    t2_times: 1
    amps: 1
    sigma: 1

  ReduceLROnPlateau:      # Learning Rate Scheduler configuration
    monitor: "epoch_loss" # Metric to monitor for reducing LR ('epoch_loss' is training loss)
    factor: 0.2           # Factor by which the learning rate will be reduced (new_lr = lr * factor)
    patience: 5           # Number of epochs with no improvement after which LR will be reduced
    # min_lr: 1e-6          # Lower bound on the learning rate
    verbose: 1            # Verbosity mode (0: silent, 1: print updates)

  ModelCheckpoint:         # Model Checkpointing configuration
    save_folder_path: *save_folder_path  # Folder path to save the model weights
    prefix: *prefix       # Prefix for the saved model files
    monitor: "epoch_loss"                          # Metric to monitor for saving the best model
    save_best_only: True                            # Whether to save only the best model
    verbose: 1                                      # Verbosity mode (0: silent, 1: print updates)

# training:
#   # model compile
#   name: *id
#   model_structure: *structure 
#   noise_model: gaussian # selections = [gaussian, rician]
#   loss: {'fitted_signals': 'categorical_crossentropy'} # categorical_crossentropy for normalization=True only
#   loss_rician_sigma: 0.08
#   optimizer:
#     name: adamax
#     learning_rate: 0.0001
#     clipnorm: Null
#     clipvalue: Null
#   metric: mae

#   # model training
#   shuffle: True
#   epochs: 100
#   batch_size: 512
#   verbose: 1 

#   # callbacks
#   TensorBoard_log_path: logs
#   TensorBoard_hist_freq: 1
#   EarlyStopping_monitor: loss
#   EarlyStopping_patience: 15
#   ReduceLROnPlateau_monitor: loss
#   ReduceLROnPlateau_factor: 0.5
#   ReduceLROnPlateau_patience: 3
#   Checkpoint_monitor: loss
#   save_best_only: True

  # paths
  # io: *paths
  # log_path: logs/training.log
  # save_model_path: *model_path



postprocessing:
  decay_model: *decay_model
  mwf_cutoff: *my_t2_cutoff
  mask_mwf_map: *mask_mwf_map
  save_maps: *save_maps 

