# same_ecos parameters to produce training data
realizations : 1000000
snr_min : 50
snr_max : 500
etl : 40 
delta_te : 6.75
T1_fix : 2000
num_t2_basis : 40
FA_min : 50
T2_min : 5
T2_max : 1000
gaussian_width : 1
exclude_M_max : True