# same_ecos parameters to produce training data for 3T GRASE data from UBC
name: SAME-ECOS training data for 64mT hyperfine MWI data
realizations: 50000
ncores: 2
snr_min: 50
snr_max: 500
etl: 120 
delta_te: 4.1
T1_fix: 2000
num_t2_basis: 40
FA_min: 50
T2_min: 5
T2_max: 1000
gaussian_width: 1
exclude_M_max: True
save_path: data/same_ecos/se_hyperfine_120echo.pickle
log_path: logs/same_ecos.log